name: Jira Check
description: Check that pull request titles contain a Jira issue.
inputs:
  ticket_pattern:
    description: 'Ticket pattern to match, e.g. "vtx-\\d+"'
    required: true
outputs:
  title:
    description: "PR title"
  url:
    description: "PR url"
runs:
  using: node12
  main: index.js
