name: Jira Check
description: Check that pull request titles contain a Jira issue.
inputs:
  ticket_id_pattern:
    description: 'Ticket ID pattern to match, e.g. "vtx-\\d+"'
    required: true
  ticket_types_pattern:
    description: 'Ticket type pattern to match, separated by "|", e.g.: "feature|bugfix"'
    required: false
runs:
  using: node12
  main: index.js
